In [5]:
import pandas as pd 
import numpy as np

In [6]:
df = pd.read_csv("synthetic_health_data (1).csv")

In [7]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,Poor,3,4,High,19.9,No,High,Yes,High
1,69,Average,2,5,High,33.9,No,Low,Yes,High
2,46,Average,7,12,Medium,31.0,Yes,Low,Yes,Medium
3,32,Good,1,11,High,38.1,No,High,No,Medium
4,60,Good,6,11,Low,34.6,No,Low,Yes,Medium

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   object
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   object
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object
 7   alcohol         4000 non-null   object
 8   family_history  4000 non-null   object
 9   risk_level      4000 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB

In [9]:
df.isnull().sum()

age               0
diet              0
exercise_days     0
sleep_hours       0
stress            0
bmi               0
smoking           0
alcohol           0
family_history    0
risk_level        0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   object
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   object
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object
 7   alcohol         4000 non-null   object
 8   family_history  4000 non-null   object
 9   risk_level      4000 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB

In [12]:
df['age'].min()

18

In [13]:
df['age'].max()

80

In [14]:
df['diet'].value_counts()

diet
Average    1987
Poor       1216
Good        797
Name: count, dtype: int64

In [15]:
df['exercise_days'].max()

7

In [16]:
df['sleep_hours'].min()

3

In [17]:
df['sleep_hours'].max()

12

In [18]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,Poor,3,4,High,19.9,No,High,Yes,High
1,69,Average,2,5,High,33.9,No,Low,Yes,High
2,46,Average,7,12,Medium,31.0,Yes,Low,Yes,Medium
3,32,Good,1,11,High,38.1,No,High,No,Medium
4,60,Good,6,11,Low,34.6,No,Low,Yes,Medium

In [19]:
categorical_col = ['diet','stress','alcohol','family_history','risk_level','smoking']

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
encoders={}

In [22]:
for i in categorical_col:
    le = LabelEncoder()
    df[i] = le.fit_transform(df[i])
    encoders[i] = le

In [23]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,2,3,4,0,19.9,0,0,1,0
1,69,0,2,5,0,33.9,0,1,1,0
2,46,0,7,12,2,31.0,1,1,1,2
3,32,1,1,11,0,38.1,0,0,0,2
4,60,1,6,11,1,34.6,0,1,1,2

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   int64
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   int64
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   int64
 7   alcohol         4000 non-null   int64
 8   family_history  4000 non-null   int64
 9   risk_level      4000 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 312.6 KB

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x= df.drop("risk_level", axis=1)
y=df['risk_level']

In [27]:
print(x.columns)

Index(['age', 'diet', 'exercise_days', 'sleep_hours', 'stress', 'bmi',
       'smoking', 'alcohol', 'family_history'],
      dtype='object')

In [28]:
print(y.name)

risk_level

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [31]:
model = LogisticRegression()

model.fit(x_train, y_train)

C:\Users\bhagy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
y_pred = model.predict(x_test)

In [39]:
acc = accuracy_score(y_test,y_pred)

In [40]:
print("accuracy score of you model ", acc)

accuracy score of you model  0.8525

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
model1 = RandomForestClassifier(n_estimators=100, random_state=42)

In [45]:
model1.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [46]:
y_predict = model1.predict(x_test)

In [47]:
acc1 = accuracy_score(y_test,y_predict)

In [48]:
print("accuracy score of you model ", acc1)

accuracy score of you model  0.96375

In [49]:
 df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,2,3,4,0,19.9,0,0,1,0
1,69,0,2,5,0,33.9,0,1,1,0
2,46,0,7,12,2,31.0,1,1,1,2
3,32,1,1,11,0,38.1,0,0,0,2
4,60,1,6,11,1,34.6,0,1,1,2

In [53]:
model1.predict([[56,2,3,4,0,19.9,0,0,1]])

C:\Users\bhagy\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])